name:                ShopAndCook
version:             0.1.0.0
github:              "githubuser/ShopAndCook"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ShopAndCook#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- servant
- servant-server
- warp
- text
- wai
- wai-extra
- wai-middleware-static
- http-media


library:
  source-dirs: src

executables:
  ShopAndCook-exe:
    main:                Main.hs
    source-dirs:         server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ShopAndCook

tests:
  ShopAndCook-test:
    main:                Spec.hs
    source-dirs:         server-test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ShopAndCook
